# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Simple-Twitter-Client' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Simple-Twitter-Client
	pod 'AFNetworking'
  	pod 'BDBOAuth1Manager' , '2.0.0'
	pod 'Alamofire', '~> 4.0'
end
